### ISSUE TITLE
Contao 4.13

### ISSUE THREAD

**Issue by AgenceUpMotion** [codefog/contao-member_content#2]
Good morning,

Is this mod still maintained?
Will it be available for contao 4.13?

**Comment by qzminski** [comment]
It should be installable on Contao 4.13. Does it not work?

**Comment by AgenceUpMotion** [comment]
I just tested, via the contao manager.

It installs without error, but does not update the database.
I just tested, via the contao manager.

It installs without error, but does not update the database.
I'm on php 8.1.4 and contao 4.13.28

**Comment by qzminski** [comment]
That's because there is nothing to be updated in the database. The extension does NOT add any new fields.

**Comment by AgenceUpMotion** [comment]
A okay,
I thought that a line was added in the member table for the icon.

How to activate this icon and therefore the module and how create a new front end module of type Member content? 

I ain't none of that
Thanks :)
![image](https://github.com/codefog/contao-member_content/assets/30799067/49a42ef4-850c-4a8b-86aa-183e2842069e)

**Comment by qzminski** [comment]
The icon should be visible right away:

![CleanShot 2023-07-25 at 16 56 31](https://github.com/codefog/contao-member_content/assets/193483/6d98cf8d-20e8-436d-afa5-a459c341dc9d)

Can you choose the `Member content` module type when creating a new frontend module?

**Comment by AgenceUpMotion** [comment]
Yes.. however I don't have it.
I don't have the member Member content.

Can you get it to work on 4.13.28?

**Comment by AgenceUpMotion** [comment]
Yes...

I tried uninstalling and reinstalling, same thing.

Clearing the dev and prod cache, the same.

I don't know what to do anymore ^^'
![image](https://github.com/codefog/contao-member_content/assets/30799067/60f7d3e8-65c1-493f-9c2f-9f0750feb7ca)

**Comment by AgenceUpMotion** [comment]
Hello,

Didn't find a problem?

I tried to reinstall it several times, everything updated, it's the same :/ Yet I don't encounter any problem during the install

**Comment by qzminski** [comment]
Can you verify that there is a folder named `/vendor/codefog/contao-member_content/` on your server?

**Comment by AgenceUpMotion** [comment]
It's OK !
I dropped the folder directly into /modules and it works fine
Thanks
